version: '3.8'

services:

  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    restart: always

  api:
    build:
      context: ./api_franquicias_back
    container_name: api_franquicias
    ports:
      - "8080:8080"
    depends_on:
      - mongo
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongo:27017/test

  frontend:
    build:
      context: ./api_franquicias_front
    container_name: frontend_franquicias
    ports:
      - "3000:80"
    depends_on:
      - api